apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/marhycz/dc-kubes-backend:main
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001